name: Deploy Shell Script Package

on:
  push:
    tags:
      - 'v*' # Dispara o workflow quando uma tag começando com 'v' é enviada (ex: v1.0, v1.2.3)

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: write    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Create and Populate Release Package
        run: |
          rsync -a . cloud-setup/ --exclude=.git --exclude=.github
          rm install.sh # Remove o script de instalação, se necessário
          tar -czvf cloud-setup_${{ github.ref_name }}.tar.gz cloud-setup/
        # O comando acima cria um arquivo .tar.gz com os scripts.
        # ${{ github.ref_name }} pega o nome da tag (ex: v1.0).

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: cloud-setup_${{ github.ref_name }}.tar.gz # Anexa o pacote à release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}